export const gradients = [
    "from-pink-400 to-transparent",
    "from-blue-400 to-transparent",
    "from-green-400 to-transparent",
    "from-purple-400 to-transparent",
    "from-gray-400 to-transparent",
    "from-red-400 to-transparent",
    "from-orange-400 to-transparent",
    "from-yellow-400 to-transparent",
    "from-green-400 to-transparent",
    "from-teal-400 to-transparent",
    "from-cyan-400 to-transparent",
    "from-blue-400 to-transparent",
    "from-indigo-400 to-transparent",
    "from-violet-400 to-transparent",
];  