export const gradients = [
    "bg-gradient-to-tl from-pink-400 to-transparent",
    "bg-gradient-to-tr from-blue-400 to-transparent",
    "bg-gradient-to-b from-green-400 to-transparent",
    "bg-gradient-to-r from-purple-400 to-transparent",
    "bg-gradient-to-r from-gray-400 to-transparent",
    "bg-gradient-to-r from-red-400 to-transparent",
    "bg-gradient-to-r from-orange-400 to-transparent",
    "bg-gradient-to-r from-yellow-400 to-transparent",
    "bg-gradient-to-r from-green-400 to-transparent",
    "bg-gradient-to-r from-teal-400 to-transparent",
    "bg-gradient-to-r from-cyan-400 to-transparent",
    "bg-gradient-to-r from-blue-400 to-transparent",
    "bg-gradient-to-r from-indigo-400 to-transparent",
    "bg-gradient-to-r from-violet-400 to-transparent",
];  